---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nodeapp
  name: node-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - image: dockerhandson/java-web-app
        name: nodeapp
        ports:
        - name: nodeapp
          containerPort: 3000  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nodeapp
  name: nodeapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: nodeapp
