apiVersion: v1
kind: ReplicationController
metadata:
  name: node-controller
spec:
  replicas: 1
  selector:
    app: nodedemo
  template:
    metadata:
      labels:
        app: nodedemo
    spec:
      containers:
      - image: vasanthkabilan91/mynode:0.0.2
        name: nodedemo
        ports:
        - containerPort: 5000  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nodeapp
  name: nodeapp
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: nodeapp
