---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: vasanthkabilan91/mynode:0.0.2
        name: nodeapp
        ports:
        - containerPort: 3000  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: nodeapp
