---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: vasanthkabilan91/mynode:0.0.2
        name: nodeapp
        ports:
        - containerPort: 5000  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: nodeapp
